from typing import Set, Dict

VENDOR_ON_PREM = 'on-prem'
VENDOR_ELASTIC_CLOUD = 'elastic-cloud'
VENDOR_ELASTIC_TRANSPORT = 'elastic-transport'
VENDOR_DIGITAL_OCEAN = 'digital-ocean'

VALID_VENDORS: Set[str] = {
    VENDOR_ON_PREM,
    VENDOR_ELASTIC_CLOUD,
    VENDOR_ELASTIC_TRANSPORT,
    VENDOR_DIGITAL_OCEAN,
}

VENDOR_DEFAULT_PORTS: Dict[str, int] = {
    VENDOR_ON_PREM: 9200,
    VENDOR_ELASTIC_CLOUD: 443,
    VENDOR_ELASTIC_TRANSPORT: 9200,
    VENDOR_DIGITAL_OCEAN: 25060,
}

TLS_PORTS: Set[int] = {443, 9243, 25060}

# Environment Variable Keys
ENV_ELASTIC_VENDOR_TYPE = ["ELASTIC_DB_VENDOR_TYPE"]
ENV_ELASTIC_HOST = ["ELASTIC_DB_HOST"]
ENV_ELASTIC_PORT = ["ELASTIC_DB_PORT"]
ENV_ELASTIC_SCHEME = ["ELASTIC_DB_SCHEME"]
ENV_ELASTIC_CLOUD_ID = ["ELASTIC_DB_CLOUD_ID"]
ENV_ELASTIC_API_KEY = ["ELASTIC_DB_API_KEY"]
ENV_ELASTIC_USERNAME = ["ELASTIC_DB_USERNAME"]
ENV_ELASTIC_PASSWORD = ["ELASTIC_DB_PASSWORD"]
ENV_ELASTIC_ACCESS_KEY = ["ELASTIC_DB_ACCESS_KEY"]
ENV_ELASTIC_API_AUTH_TYPE = ["ELASTIC_DB_API_AUTH_TYPE"]
ENV_ELASTIC_USE_TLS = ["ELASTIC_DB_USE_TLS"]
ENV_ELASTIC_VERIFY_CERTS = ["ELASTIC_DB_VERIFY_CERTS"]
ENV_ELASTIC_SSL_SHOW_WARN = ["ELASTIC_DB_SSL_SHOW_WARN"]
ENV_ELASTIC_CA_CERTS = ["ELASTIC_DB_CA_CERTS"]
ENV_ELASTIC_CLIENT_CERT = ["ELASTIC_DB_CLIENT_CERT"]
ENV_ELASTIC_CLIENT_KEY = ["ELASTIC_DB_CLIENT_KEY"]
ENV_ELASTIC_INDEX = ["ELASTIC_DB_INDEX"]
ENV_ELASTIC_VERIFY_CLUSTER = ["ELASTIC_DB_VERIFY_CLUSTER_CONNECTION"]
ENV_ELASTIC_REQUEST_TIMEOUT = ["ELASTIC_DB_REQUEST_TIMEOUT"]
ENV_ELASTIC_CONNECT_TIMEOUT = ["ELASTIC_DB_CONNECT_TIMEOUT"]
ENV_ELASTIC_MAX_RETRIES = ["ELASTIC_DB_MAX_RETRIES"]
ENV_ELASTIC_RETRY_ON_TIMEOUT = ["ELASTIC_DB_RETRY_ON_TIMEOUT"]
