from typing import Set, Dict

VENDOR_ON_PREM = 'on-prem'
VENDOR_ELASTIC_CLOUD = 'elastic-cloud'
VENDOR_ELASTIC_TRANSPORT = 'elastic-transport'
VENDOR_DIGITAL_OCEAN = 'digital-ocean'

VALID_VENDORS: Set[str] = {
    VENDOR_ON_PREM,
    VENDOR_ELASTIC_CLOUD,
    VENDOR_ELASTIC_TRANSPORT,
    VENDOR_DIGITAL_OCEAN,
}

VENDOR_DEFAULT_PORTS: Dict[str, int] = {
    VENDOR_ON_PREM: 9200,
    VENDOR_ELASTIC_CLOUD: 443,
    VENDOR_ELASTIC_TRANSPORT: 9200,
    VENDOR_DIGITAL_OCEAN: 25060,
}

TLS_PORTS: Set[int] = {443, 9243, 25060}
