export const VENDOR_ON_PREM = "on-prem";
export const VENDOR_ELASTIC_CLOUD = "elastic-cloud";
export const VENDOR_ELASTIC_TRANSPORT = "elastic-transport";
export const VENDOR_DIGITAL_OCEAN = "digital-ocean";

export const VALID_VENDORS = new Set([
    VENDOR_ON_PREM,
    VENDOR_ELASTIC_CLOUD,
    VENDOR_ELASTIC_TRANSPORT,
    VENDOR_DIGITAL_OCEAN,
]);

export const VENDOR_DEFAULT_PORTS: Record<string, number> = {
    [VENDOR_ON_PREM]: 9200,
    [VENDOR_ELASTIC_CLOUD]: 443,
    [VENDOR_ELASTIC_TRANSPORT]: 9200,
    [VENDOR_DIGITAL_OCEAN]: 25060,
};

export const TLS_PORTS = new Set([443, 9243, 25060]);

// Environment Variable Keys
export const ENV_ELASTIC_VENDOR_TYPE = ["ELASTIC_DB_VENDOR_TYPE"];
export const ENV_ELASTIC_HOST = ["ELASTIC_DB_HOST"];
export const ENV_ELASTIC_PORT = ["ELASTIC_DB_PORT"];
export const ENV_ELASTIC_SCHEME = ["ELASTIC_DB_SCHEME"];
export const ENV_ELASTIC_CLOUD_ID = ["ELASTIC_DB_CLOUD_ID"];
export const ENV_ELASTIC_API_KEY = ["ELASTIC_DB_API_KEY"];
export const ENV_ELASTIC_USERNAME = ["ELASTIC_DB_USERNAME"];
export const ENV_ELASTIC_PASSWORD = ["ELASTIC_DB_PASSWORD"];
export const ENV_ELASTIC_ACCESS_KEY = ["ELASTIC_DB_ACCESS_KEY"];
export const ENV_ELASTIC_API_AUTH_TYPE = ["ELASTIC_DB_API_AUTH_TYPE"];
export const ENV_ELASTIC_USE_TLS = ["ELASTIC_DB_USE_TLS"];
export const ENV_ELASTIC_VERIFY_CERTS = ["ELASTIC_DB_VERIFY_CERTS"];
export const ENV_ELASTIC_SSL_SHOW_WARN = ["ELASTIC_DB_SSL_SHOW_WARN"];
export const ENV_ELASTIC_CA_CERTS = ["ELASTIC_DB_CA_CERTS"];
export const ENV_ELASTIC_CLIENT_CERT = ["ELASTIC_DB_CLIENT_CERT"];
export const ENV_ELASTIC_CLIENT_KEY = ["ELASTIC_DB_CLIENT_KEY"];
export const ENV_ELASTIC_INDEX = ["ELASTIC_DB_INDEX"];
export const ENV_ELASTIC_VERIFY_CLUSTER = ["ELASTIC_DB_VERIFY_CLUSTER_CONNECTION"];
export const ENV_ELASTIC_REQUEST_TIMEOUT = ["ELASTIC_DB_REQUEST_TIMEOUT"];
export const ENV_ELASTIC_CONNECT_TIMEOUT = ["ELASTIC_DB_CONNECT_TIMEOUT"];
export const ENV_ELASTIC_MAX_RETRIES = ["ELASTIC_DB_MAX_RETRIES"];
export const ENV_ELASTIC_RETRY_ON_TIMEOUT = ["ELASTIC_DB_RETRY_ON_TIMEOUT"];
